ajax_guide/urls.py
from app_1 import views as app1
from app_2 import views as app2
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from app_1.views import signup
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    # app_1
    #FBV
    path('', app1.index, name = 'index'),
    path('index', app1.index, name='index'),
    #path('', app1.contactPage),
    path('contact', app1.contactPage),
    path('ajax/contact', app1.postContact, name = 'contact_submit'),
    path('add', app1.addPost, name='add'),
    path('ajax/add', app1.ajxAddPost, name='add_post'),
    path('delete', app1.deletePost, name='delete'),
    path('edit/<int:id>', app1.editPost, name='edit'),
    path('view/<slug:slug>', app1.viewPost, name='view_post'),
    
    #CBV
    path('contact_cbv', app1.ContactAjax.as_view(), name = 'contact_submit_cbv'),
    #all posts
    path('posts', app1.userPosts, name='posts'),
    path('load', app1.loadPosts, name='load'),
    path('loadscroll', app1.loadscroll, name='loadscroll'),
    path('profile', app1.profile, name='profile'),
    path('upprofile', app1.upprofile, name='upprofile'),
    
    #auth login
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', signup.as_view(), name='signup'),
    path('auth', app1.loginUser, name='auth'),
    path('register', app1.registerUser, name='register'),
    path('search', app1.search, name='search'),

    #app_2
    path('user', app2.userPanel, name='user'),
    path('ajax/get_user_info', app2.getUserInfo, name = 'get_user_info'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_1/models.py
from django.db import models
from django.utils.text import slugify
from .utils import random_string_generator
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from PIL import Image
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Contact(models.Model):
	id 			= models.BigAutoField(primary_key=True)
	name 		= models.CharField(max_length = 100)
	email 		= models.EmailField()
	message 	= models.TextField()
	timestamp 	= models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return self.name



def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]



class Posts(models.Model):
	id 			= models.BigAutoField(primary_key=True)
	fc_post 	= models.DateTimeField(auto_now_add=True, null=True)
	act_post 	= models.IntegerField(default=1)
	nom_post 	= models.CharField(max_length=200)
	desc_post 	= models.TextField()
	img_post 	= models.ImageField(upload_to='images/', default="")
	slug_post 	= models.SlugField(max_length=200, unique=True, editable=False)
	#user 		= models.OneToOneField(User, on_delete=models.CASCADE)
	user 		= models.ForeignKey(User, null=True, related_name='user',  on_delete=models.SET(get_sentinel_user),)  # models.IntegerField()

	def save(self, *args, **kwargs):
		new_slug 		= "{slug}-{randstr}".format(slug=" ".join(self.nom_post.split()[:4]), randstr=random_string_generator(size=4))
		self.slug_post 	= slugify(new_slug, allow_unicode=False)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.nom_post



"""class UserProfile(models.Model):
	profile_user = models.OneToOneField(User, on_delete=models.CASCADE)
	profile_img = models.ImageField(default='default.png', upload_to='profile_pics')"""

class Profile(models.Model):
	id 		= models.BigAutoField(primary_key=True)
	image = models.ImageField(default='default.svg', upload_to='profile_pics')
	user 	= models.OneToOneField(User, on_delete=models.CASCADE)
	
	"""def __str__(self):
		return f'{self.user.username} Profile'"""

	"""def save(self):
		super().save()
		img = Image.open(self.image.path)
		if img.height > 300 or img.width > 300:
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.image.path)"""


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)
	instance.profile.save()



"""class bk_Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	#portfolio_site = models.URLField(blank=True)
	image = models.ImageField(upload_to='profile_pics', blank=True, default='default.jpg')

	def __str__(self):
		return self.user.username"""

app_1/forms.py
from django import forms
from .models import Contact, Posts
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		exclude = ["timestamp", ]
		widgets = {
			'message': forms.Textarea(attrs={'rows':4, 'cols':15}),
		}

	def __init__(self, *args, **kwargs):
		super(ContactForm, self).__init__(*args, **kwargs)
		for field in self.fields:
			self.fields[field].widget.attrs.update({'class': 'form-control'})



class AddPostForm(forms.ModelForm):
	class Meta:
		model = Posts
		fields = ["act_post", "nom_post", "desc_post", "img_post", "user"]
		exclude = ["timestamp", ]
		widgets = {
			'desc_post': forms.Textarea(attrs={'rows': 4, 'cols': 15}),
		}

	def __init__(self, *args, **kwargs):
		super(AddPostForm, self).__init__(*args, **kwargs)
		for field in self.fields:
			self.fields[field].widget.attrs.update({'class': 'form-control'})



class UserRegisterForm(UserCreationForm):
	#email = forms.EmailField()
	class Meta:
		model = User
		fields = ['username', 'password1']



class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']



class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['image']


"""class ProfileUpdateForm(forms.ModelForm):
	class Meta():
		model = Profile
		fields = ["image"]

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		#self.fields["portfolio_site"].label = "Site"
		self.fields["image"].label = "Image"""

app_1/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect, render
from django.http import JsonResponse
from .forms import ContactForm, AddPostForm
from django.views import View
from .models import Posts, Profile
import math
from .utils import paginate
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, ProfileUpdateForm, UserRegisterForm
# Create your views here.


def index(request):
	posts = Posts.objects.all().values("id", "nom_post", "fc_post", 'slug_post', 'user_id', 'img_post').order_by("-id")
	return render(request, "main.html", {"posts": posts})

#FBV
def contactPage(request):
	form = ContactForm()
	return render(request, "contact.html", {"contactForm": form})


def postContact(request):
	if request.method == "POST" and request.is_ajax():
		form = ContactForm(request.POST)
		form.save()
		return JsonResponse({"tipo": "success", "icon": "bi bi-check-circle", "msg": "Post agregado", "success": True}, status=200)
	return JsonResponse({"tipo": "danger", "icon": "bi bi-x-circle", "msg": "Error interno, intenta más tarde.", "success": False}, status=400)


def addPost(request):
	if request.user.is_authenticated:
		form = AddPostForm()
		return render(request, "addPost.html", {"form": form})
	return redirect('login')



def ajxAddPost(request):
	if request.user.is_authenticated:
		if request.method == "POST" and request.is_ajax():
			form = AddPostForm(request.POST, request.FILES)
			if form.is_valid():
				form.save()
				return JsonResponse({"tipo": "success", "icon": "bi bi-check-circle", "msg": "Registro agregado correctamente", "success": True}, status=200)
			else:
				return JsonResponse({"tipo": "danger", "icon": "bi bi-x-circle", "msg": "Error en la validación del formulario.", "success": False}, status=400)
		else:
			return JsonResponse({"tipo": "danger", "icon": "bi bi-x-circle", "msg": "Error interno, intenta más tarde.", "success": False}, status=400)
	else:
		return JsonResponse({"tipo": "danger", "icon": "bi bi-x-circle", "msg": "Por favor inicia sesión.", "success": False}, status=400)



def viewPost(request, slug):
	if request.method == "GET":
		try:
			post = Posts.objects.get(slug_post=slug)
			exist = True
		except:
			post = False
			exist = False
	else:
		post = False
		exist = False
	return render(request, "viewPost.html", {"post": post, "exist": exist})



#CBV
class ContactAjax(View):
	form_class = ContactForm
	template_name = "contact_cbv.html"

	def get(self, *args, **kwargs):
		form = self.form_class()
		return render(self.request, self.template_name, {"contactForm": form})

	def post(self, *args, **kwargs):
		if self.request.method == "POST" and self.request.is_ajax():
			form = self.form_class(self.request.POST)
			form.save()
			return JsonResponse({"tipo":"success","icon":"bi bi-check-circle", "msg":"Registro agregado correctamente","success":True}, status=200)
		return JsonResponse({"tipo": "danger", "icon": "bi bi-x-circle", "msg": "Error interno, intenta más tarde.", "success": False}, status=400)


def userPosts(request):
	if request.user.is_authenticated:
		posts = Posts.objects.all().values("id", "nom_post", "fc_post", 'slug_post', 'user')
		return render(request, "userPosts.html", {"posts": posts})
	return redirect('login')



def loadPosts(request):
	user_id = None
	if request.user.is_authenticated:
		user_id = request.user.id
		if request.method == "POST" and request.is_ajax():
			record 		= int(request.POST.get('page'))
			edo 		= int(request.POST.get('filter'))
			order_by 		= request.POST.get('order_by')
			order = request.POST.get('order')
			page 		= record if record>0 else 1
			per_page 	= int(request.POST.get('limite'))
			offset 		= (page - 1) * per_page
			search 		= request.POST.get('search')
			total 		= 0;
			if edo==2 :
				total = Posts.objects.filter(
					nom_post__icontains=search, user=user_id).count()
				posts = Posts.objects.filter(nom_post__icontains=search, user=user_id).order_by(
					order+order_by).all()[offset:offset+per_page]
			else:
				total = Posts.objects.filter(
					act_post=edo, nom_post__icontains=search, user=user_id).count()
				posts = Posts.objects.filter(act_post=edo, nom_post__icontains=search, user=user_id).order_by(
					order+order_by).all()[offset:offset+per_page]
			
			if total > 0:
				total_pages = math.ceil(total/per_page)
				adyacentes 	= 2
				data = ""
				data += '<div class="table-responsive">'
				data += '<table class="table table-hover table-fixed">'
				data += '<thead>'
				data += '<tr class="row-link">'
				data += '<th class="text-left w-10">'
				data += '<div class="checkbox checkbox-danger" style="display: inline;">'
				data += '<input id="chk-all-regs" type="checkbox">'
				data += '<label for="chk-all-regs" style="padding-bottom: 15px;"> </label>'
				data += '</div>'
				data += '<button class="btn btn-sm quick-btn btn-link text-danger mdl-del-regs" id="btn-del-list" title="Eliminar seleccionados" data-bs-toggle="modal" data-bs-target="#mdl-del-regs" disabled="disabled">'
				data += '<i class="bi bi-trash"> </i>'
				data += '<i id="spn-del" class="spn-total"> </i>'
				data += '</button>'
				data += '</th>'
				data += '<th data-field="id" class="th-link text-left"> <i class="fas fa-sort"> </i>  # </th>'
				data += '<th data-field="nom_post" class="th-link"> <i class="fas fa-sort"> </i> Nombre </th>'
				data += '<th class = "text-center w-10" > Acciones </th>'
				data += '</tr>'
				data += '</thead>'
				data += '<tbody>'

				for post in posts:
					data += '<tr id="row-id-'+str(post.id)+'">'
					data += '<td class="text-left">'
					data += '<div class="checkbox checkbox-primary">'
					data += '<input type="checkbox" class="chks-regs" name="chk-reg-'+str(post.id)+'" id="chk-reg-'+str(post.id)+'" data-iddel="'+str(post.id)+'">'
					data += '<label for="chk-reg-'+str(post.id)+'"> </label>'
					data += '</div>'
					data += '</td>'
					data += '<td class="text-left">'+str(post.id)+'</td>'
					data += '<td>'
					data += '<a href="view/'+post.slug_post+'"> '+post.nom_post+'</a></td>'
					data += '<td class="text-center">'
					data += '<a href="edit/'+str(post.id)+'" class="btn btn-primary btn-sm"><i class="bi bi-pencil-square"></i></a> '
					data += ' <button type="button" class="btn btn-danger mdl-del-reg btn-sm" title="Eliminar" data-bs-toggle="modal" data-bs-target="#mdl-del-reg" data-idreg="'+str(post.id)+'" data-nomreg="'+post.nom_post+'">'
					data += '<i class="bi bi-trash"> </i></button></td></tr>'

				data += '</tbody></table></div>'
				return JsonResponse({"total": total, "data": data, "paginate": paginate(page, total_pages, adyacentes, "load"), "success": True}, status=200)
			else:
				return JsonResponse({"total": total, "data": '<div class="text-center alert alert-info" role="alert"><i class="bi bi-info-circle"></i> Sin resultados.</div>', "paginate": "", "success": True}, status=200)
		else:
			return JsonResponse({"total": "0", "data": '<div class="text-center alert alert-danger" role="alert"><i class="bi bi-x-circle"></i> Error interno, intenta más tarde.</div>', "success": False}, status=400)
	else:
		return JsonResponse({"total": "0", "data": '<div class="text-center alert alert-danger" role="alert"><i class="bi bi-x-circle"></i> Por favor inicia sesión.</div>', "success": False}, status=400)



def loadscroll(request):
	if request.method == "POST" and request.is_ajax():
		order_by = request.POST.get('order_by')
		order = request.POST.get('order')
		search = request.POST.get('search')
		start = int(request.POST.get('start'))
		limit = int(request.POST.get('limit'))

		total = 0
		total = Posts.objects.filter(act_post=1, nom_post__icontains=search).count()
		posts = Posts.objects.filter(act_post=1, nom_post__icontains=search).order_by(order+order_by).all()[start:start+limit]

		if total > 0:
			data = ""
			for post in posts:
				formatedDate = post.fc_post.strftime("%b %d, %Y")
				img = '/media/' + \
					str(post.img_post) if post.img_post else 'static/img/post.png'
				data += '<div class="col-lg-4 col-md-4 col-sm-6 col-xs-6 mb-2 d-flex">'
				data += '<div class="card mb-2 post border-bottom-2" style="width:100%;">'
				data += '<a href="view/'+post.slug_post+'">'
				data += '<div class="post-image rounded">'
				data += '<img src="'+str(img)+'" class="" alt="" sizes="(max-width: 272px) 100vw, 272px">'
				data += '</div>'
				data += '</a>'
				data += '<div class="card-body font-weight-bold ">'
				data += '<a class="text-dark" href="view/'+post.slug_post+'">'+post.nom_post+'</a><div>'
				data += '<small class="float float-right"> <span class="byline-author-label"> By </span>'
				data += '<a class="byline-author-name-link" href="#" title="LiNuXiToS"> '+post.user.username+' </a> </small>'
				data += '<small class="float-end"> '+(str(formatedDate))+' </small></div></div></div></div>'
			return JsonResponse({"total": total, "data": data, "search":search, "success": True}, status=200)
		else:
			return JsonResponse({"total": total,"search":search, "data": '<div class="col-md-12"><div class="text-center alert alert-info" role="alert"><i class="bi bi-info-circle"></i> Sin resultados.</div></div>', "paginate": "", "success": True}, status=200)
	else:
		return JsonResponse({"total": "0", "search": "", "data": '<div class="col-md-12"><div class="text-center alert alert-danger" role="alert"><i class="bi bi-x-circle"></i> Error interno, intenta más tarde.</div></div>', "success": False}, status=400)



def deletePost(request):
	if request.user.is_authenticated:
		if request.method == "POST" and request.is_ajax():
			ids = request.POST.get('list_ids').split('|')
			for id in ids:
				act_post = int(request.POST.get('act_post'))

app_1/templates/addPost.html
{% extends "base.html" %}
{% block head %}
	<title>Add post | linuxitos</title>
{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
	{% if user.is_authenticated %}
		<div class="container mt-5">
			<div class="row mt-5">
				<div class="col-md-12 mt-5">
					<nav aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="/">Inicio</a></li>
							<li class="breadcrumb-item"><a href="{%url 'posts'%}">Posts</a></li>
							<li class="breadcrumb-item active" aria-current="page">Agregar post</li>
						</ol>
					</nav>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">Agregar nuevo post</h5>
							<div class="row justify-content-center align-items-center">
								<div id="div-cnt-msg-add" class="col-sm-12"></div>
								<div class="col-sm-12">
									<form id="form-add-post" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
										{% csrf_token %}
										<input type="hidden" name="user" id="id_user" readonly="" value="{{user.id}}">
										<div class="row">
											<div class="col-md-3">
												<div id="div-cnt-img-ajx" class="post-image rounded">
													<img src="static/img/post.png" class="" alt="" sizes="(max-width: 272px) 100vw, 272px">
												</div>
												<div class="input-group mb-2 mt-2">
													<input type="file" class="form-control" id="id_img_post" name="img_post" onchange="readURL(this, 'div-cnt-img-ajx');" accept=".png, .jpg, .jpeg">
												</div>
											</div>
											<div class="col-md-9">
												<div class="row">
													<div class="col-6">
														<label for="id_nom_post">Nombre:</label>
														<input type="text" name="nom_post" maxlength="100" class="form-control" required="" id="id_nom_post" autocomplete="off">
													</div>
													<div class="col-6">
														<label for="id_act_post">Estado:</label>
														<select class="form-select" aria-label="Default select example" name="act_post" id="id_act_post" required="">
															<option value="1" selected="">Activo</option>
															<option value="0">Inactivo</option>
														</select>
													</div>
													<div class="col-12">
														<label for="id_desc_post">Descripción:</label>
														<textarea name="desc_post" cols="15" rows="2" class="form-control" required="" id="id_desc_post"></textarea>
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12 mt-2 mb-2">
												<button type="submit" name="contact-submit" class="btn btn-primary float-end" id="btn-register">
													<i class="bi bi-check-circle"></i> Agregar
												</button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% else %}
		<script>
			/*$(document).ready(function () {
				var url = "{% url 'login' %}";
				$(location).attr('href', url);
			});*/
		</script>
	{% endif %}
{% endblock %}
{% block script %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("#form-add-post").submit(function(e){
				$('#btn-register').attr("disabled", true);
				//var serializedData = $(this).serialize();
				form = $(this)
				var formData = new FormData(this);
				$.ajax({
					method: 	"POST",
					type : 		"POST",
					//processData: false,
					//contentType: false,
					dataType: 	"JSON",
					cache: false,
					contentType: false,
					processData: false,
					url :  		"{% url 'add_post' %}",
					//data : 	serializedData,
					data: 		formData,
					beforeSend: function (objeto) {
						$("#div-cnt-msg-add").html('<div class="alert alert-info" role="alert">' +
							'<span class="spinner-border spinner-border-sm spin-x" role="status" aria-hidden="true"></span> Guardando...' + '</div>');
						$('#btn-register').html('<span class="spinner-border spinner-border-sm spin-x" role="status" aria-hidden="true"></span> Guardando...');
					},
					success : function(response){
						console.log(response);
						$('#btn-register').attr("disabled", false);
						//$("#btn-close-del-estab").trigger("click");
						//notify_msg(response.icon, " ", response.msg, "#", response.tipo);
						if (response.tipo=="success") {
							$("#form-add-post")[0].reset();
							$("#div-cnt-img-ajx").html('<img src="static/img/post.png" class="" alt="" sizes="(max-width: 272px) 100vw, 272px">')
						}
						$("#div-cnt-msg-add").html('<div class="alert alert-' + response.tipo + ' alert-dismissible fade show" role="alert"><i class="' + response.icon + '"></i> ' + response.msg + '</div>');
						$('#btn-register').html('<i class="bi bi-check-circle"></i> Agregar');
						setTimeout(function () {
							$("#div-cnt-msg-add").html("");
						}, 3000);
					},
					error : function(response){
						console.log(response);
						$('#btn-register').attr("disabled", false);
						$('#btn-register').html('<i class="bi bi-x-circle"></i> Agregar');
						$("#div-cnt-msg-add").html('<div class="alert alert-danger alert-dismissible fade show" role="alert"><i class="bi bi-x-circle"></i> Error interno, intenta más tarde.</div>');
						setTimeout(function () {
							$("#div-cnt-msg-add").html("");
						}, 3000);
					}
				});
				e.preventDefault();
			});
		});
		
		function readURL(input, div) {
			var total_files = $(input)[0].files.length;
			$("#" + div).html('');
			for (i = 0; i < total_files; i++) {
				if ($(input)[0].files[i]) {
					var reader = new FileReader();
					reader.onload = function (e) {
						$("#" + div).append('<div class="col-md-12"><img id="img-' + i + '" src="' + e.target.result + '" class="img-fluid"/></div>')
					};
					reader.readAsDataURL(input.files[i]);
				}
			}
		}
	</script>
{% endblock %}

app_1/templates/modals.html
<!-- Modal -->
<div class="modal fade" id="mdl-add-reg" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form id="form-add-post" name="form-add-post" accept-charset="utf-8" enctype="multipart/form-data">
				{% csrf_token %}
				<input type="hidden" name="user" value="{{user.id}}" id="id_user" readonly="">
				<div class="modal-header bg-mdl-add">
					<h5 class="modal-title"><i class="fa fa-pencil"></i> Agregando</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-md-12 text-center" id="div-cnt-msg-add-reg"></div>
					</div>
					<div class="row">
						<div class="col-md-12 mb-3">
							<div class="form-group input-group">
								<span class="has-float-label">
									<input type="text" class="form-control" name="nom_post" id="id_nom_post" placeholder="Nombre" required="required" value="" autocomplete="off">
									<label for="id_nom_post">Nombre</label>
								</span>
							</div>
						</div>
						<div class="col-md-12 mb-3">
							<select class="form-select" aria-label="Default select example" name="act_post" id="id_act_post" required="">
								<option value="1" selected="">Activo</option>
								<option value="0">Inactivo</option>
							</select>
						</div>
						<div class="col-md-12 mb-3">
							<div class="mb-3">
								<label for="id_desc_post" class="form-label">Contenido</label>
								<textarea class="form-control txt-desc" name="desc_post" id="id_desc_post" rows="3"></textarea>
							</div>
							<!--div class="form-group input-group">
								<span class="has-float-label">
									<input type="text" class="form-control" name="txt-desc-add" id="txt-desc-add" placeholder="Descripción" required="required" value="" autocomplete="off">
									<label for="txt-desc-add">Descripción</label>
								</span>
							</div-->
						</div>
						<div class="col-md-6 mb-3">
							<div class="input-group">
								<div class="custom-file">
									<input type="file" class="custom-file-input form-control" id="id_img_post" name="img_post" accept=".png, .jpg, .jpeg">
								</div>
							</div>
						</div>
						<div class="col-md-6 p-1">
							<div id="div-cnt-img-ajx"></div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="btn-close-mdl-add-reg">
						<i class="bi bi-x-circle"></i> Cancelar
					</button>
					<button type="submit" class="btn btn-success" id="btn-register">
						<i class="bi bi-check2-circle"></i> Agregar
					</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="modal fade app-mdl" id="mdl-del-regs" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header bg-mdl-del p-2">
				<h5 class="modal-title"><i class="fa fa-trash-alt"></i> Eliminando</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<form class="form" method="post" id="form-del-regs" name="form-del-regs">
				<div class="modal-body">
					<div class="row">
						<div class="col-md-12 text-center" id="div-cnt-del-list-regs"></div>
					</div>
					<div class="row">
						<div class="col-md-12 text-center" id="div-cnt-del-regs"></div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" id="btn-close-mdl-del-regs" class="btn btn-secondary" data-bs-dismiss="modal">
						<i class="fa fa-times"></i> Cerrar
					</button>
					<button type="submit" class="btn btn-danger" id="btn-del-regs">
						<i class="fa fa-trash-alt"></i> Eliminar
					</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="modal fade app-mdl" id="mdl-del-reg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header bg-mdl-del">
				<h5 class="modal-title"><i class="bi bi-trash"></i> Eliminando</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<form method="post" id="form-del-reg" name="form-del-reg">
				{% csrf_token %}
				<div class="modal-body">
					<div class="row">
						<div class="col-md-12 text-center" id="div-cnt-del-reg"></div>
					</div>
					<input type="hidden" id="txt-id-reg-del" name="list_ids" readonly="" value="0">
					<div class="row">
						<div class="col-md-12 text-center" id="div-cnt-del-reg">
							<h5>
								Seleccione la acción para <b class="text-danger" id="txt-nom-reg"></b>
							</h5>
						</div>
						<div class="col-md-12">
							<select class="form-select" aria-label="Default select example" name="act_post" id="slt-act-post" required="">
								<option selected="" value="" disabled> Seleccionar</option>
								<option value="1">Activar</option>
								<option value="0">Eliminar</option>
							</select>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" id="btn-close-mdl-del-reg" class="btn btn-secondary" data-bs-dismiss="modal">
						<i class="bi bi-x-lg"></i> Cerrar
					</button>
					<button type="submit" class="btn btn-danger" id="btn-del-reg">
						<i class="bi bi-trash"></i> Eliminar
					</button>
				</div>
			</form>
		</div>
	</div>
</div>